# Aljabar Matrix
# Tidak mengerjakan tidak boleh masuk 

   - Berikan pengertian apa itu Aljabar matrix
   -Buatlah Matrix A(3x3),B(2x3),C(3x2)
   - Operasi Matrix
      -  Penjumlahan
      - Perkalian
      - Pengurangan
      - Tranpose Matrix
   - Buat program untuk mengkalikan Matrix A dengan Matrix B tidak menggunakan '@'

Pengertian Matrix: Matrix merupakan suatu kumpulan bilangan sejumlah m x n yang disusun menjadi m baris dan n kolom.

In [1]:
import numpy as np

In [2]:
# Matrix
a = np.array([[2,5,8],[3,2,5],[9,5,2]]) # matrix 3x3
b = np.array([[2,9,5],[-2,3,6],[1,-2,5]]) # matrix 3x3
c = np.array([[3,4],[-3,2],[6,9]]) # matrix 3x2
d = np.array([[2,5,8],[2,-1,6],[8,-5,2]]) # matrix 3x3
e = (a+b)
f = 2*(a)
g = a @ c

In [3]:
print(f"Matrix A 3x3: \n{a}")
print(f" Matrix B 3x3: \n{b}")
print(f"Matrix C 3x2: \n{c}")
print(f"Matrix D 3x3: \n{d}")

Matrix A 3x3: 
[[2 5 8]
 [3 2 5]
 [9 5 2]]
 Matrix B 3x3: 
[[ 2  9  5]
 [-2  3  6]
 [ 1 -2  5]]
Matrix C 3x2: 
[[ 3  4]
 [-3  2]
 [ 6  9]]
Matrix D 3x3: 
[[ 2  5  8]
 [ 2 -1  6]
 [ 8 -5  2]]


# Operasi Penjumlahan Matrix

In [4]:
# Matrix A+B
e = (a+b)
print(f"Matrix E =\n{e}")

Matrix E =
[[ 4 14 13]
 [ 1  5 11]
 [10  3  7]]


# operasi perkalian matrix


In [5]:
f = 2*(a)

print(f"Perkalian 2 * Matrix F =\n{f}")

Perkalian 2 * Matrix F =
[[ 4 10 16]
 [ 6  4 10]
 [18 10  4]]


In [6]:
# Matrix A x C
g = a @ c
print(f"Matrix G =\n{g}")
print(f"Ukuran Matrix = {g.shape}")

Matrix G =
[[39 90]
 [33 61]
 [24 64]]
Ukuran Matrix = (3, 2)


# operasi pengurangan matrix

In [7]:
# Matrix A - B
h  = a - b
print(f"Matrix G =\n{h}")

Matrix G =
[[ 0 -4  3]
 [ 5 -1 -1]
 [ 8  7 -3]]


# Cek Persamaan
Matrix A(BxC) = Matrix (AxB)C

In [8]:
Matrix1 = a @ (b @ c)
Matrix2 = (a @ b) @ c
Matrix1 == Matrix2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Matrix c(AB) = Matrix (cA)B = Matrix A(cB)

In [9]:
c = 2
Matrix_3 = c * (a @ b)
Matrix_4 = (c * a) @ b
Matrix_5 = a @ (c * b)
print(Matrix_3)
print()
print(Matrix_4)
print()
print(Matrix_5)

[[  4  34 160]
 [ 14  46 104]
 [ 20 184 170]]

[[  4  34 160]
 [ 14  46 104]
 [ 20 184 170]]

[[  4  34 160]
 [ 14  46 104]
 [ 20 184 170]]


# Tranpose Matrix

Anggap Baris = m, Kolom = n

=> C = A_trans @ A

=> (n x m) @ (m x n) = n * n

contoh: [2 x 3] @ [3 x 2] = [2 x 2]

=> C = A @ A_trans

=> (m x n) @ (n x m) = m x m

contoh: [3 x 2] @ [2 x 3] = [3 x 3]

In [10]:
# Contoh dengan Martrix 3x3

a_tran = a.transpose()
print('Matrik A sebelum di transpose=\n', a)
print()
print('Matrik A setelah di transpose=\n',a_tran)
print('Ordo A_transpose adalah',a_tran.shape)
print()
Z = a_tran @ a
print('Z = A_transpose x A =\n',Z)
print('Ordo Z adalah',Z.shape)
print()
P=a @ a_tran
print('P = A_transpose x A =\n',P)
print('Ordo P adalah',P.shape)

Matrik A sebelum di transpose=
 [[2 5 8]
 [3 2 5]
 [9 5 2]]

Matrik A setelah di transpose=
 [[2 3 9]
 [5 2 5]
 [8 5 2]]
Ordo A_transpose adalah (3, 3)

Z = A_transpose x A =
 [[94 61 49]
 [61 54 60]
 [49 60 93]]
Ordo Z adalah (3, 3)

P = A_transpose x A =
 [[ 93  56  59]
 [ 56  38  47]
 [ 59  47 110]]
Ordo P adalah (3, 3)


In [11]:
# Soal dengan Matrix 3x2

Matrix_A = np.array([[-1,4,7],[-3,5,9]])

Matrix_A_Trans = Matrix_A.transpose()
print('Matrix_A sebelum di transpose=\n', Matrix_A)
print()

print('Matrix A setelah di transpose=\n',Matrix_A_Trans)
print('Ordo Matrix_A_Transpose adalah',Matrix_A_Trans.shape)
print()

Matrix_Z = Matrix_A_Trans @ Matrix_A
print('Matrix_Z = Matrix_A_Transpose x Matrix_A =\n',Matrix_Z)
print('Ordo Z adalah',Z.shape)
print()

Matrix_P = Matrix_A @ Matrix_A_Trans
print('P = A_transpose x A =\n',Matrix_P)
print('ordo Matrix P adalah',Matrix_P.shape)

Matrix_A sebelum di transpose=
 [[-1  4  7]
 [-3  5  9]]

Matrix A setelah di transpose=
 [[-1 -3]
 [ 4  5]
 [ 7  9]]
Ordo Matrix_A_Transpose adalah (3, 2)

Matrix_Z = Matrix_A_Transpose x Matrix_A =
 [[ 10 -19 -34]
 [-19  41  73]
 [-34  73 130]]
Ordo Z adalah (3, 3)

P = A_transpose x A =
 [[ 66  86]
 [ 86 115]]
ordo Matrix P adalah (2, 2)


# Program untuk mengkalikan Matrix A dengan Matrix B Secara Manual tidak menggunakan ‘@’

In [12]:
Matrix_1 = [[1,-3,9],
            [3,-4,6],
            [9,4,-1]]

Matrix_2 = [[1,7,2],
            [-2,4,9],
            [1,7,4]]

print(f" Matrix_1 = {Matrix_1}")
print()
print(f" Matrix_2 = {Matrix_2}")

def multiply_matrix(matrix1,matrix2):
  result = [[0,0,0],[0,0,0],[0,0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(Matrix_1)):
    for j in range(len(Matrix_2[0])):
      for k in range(len(Matrix_2)):
        result[i][j] += Matrix_1[i][k] * Matrix_2[k][j]
  return result

hasil = multiply_matrix(Matrix_1,Matrix_2)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print()
print(f"Pembuktian untuk Matrix A @ B =\n{a @ b}")

 Matrix_1 = [[1, -3, 9], [3, -4, 6], [9, 4, -1]]

 Matrix_2 = [[1, 7, 2], [-2, 4, 9], [1, 7, 4]]

Hasil perkalian Matrix_1 dan Matrix 2 = [[16, 58, 11], [17, 47, -6], [0, 72, 50]]

Pembuktian untuk Matrix A @ B =
[[ 2 17 80]
 [ 7 23 52]
 [10 92 85]]


In [13]:
# Ini yang menggunakan numpy array

print(f" Matrix_1 = \n{a}")
print()
print(f" Matrix_2 = \n{b}")

def multiply_matrix(matrix1,matrix2):
  result = [[0,0,0],[0,0,0],[0,0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(a)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        result[i][j] += a[i][k] * b[k][j]
  return result

hasil = multiply_matrix(a,b)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print()
print(f"Pembuktian untuk Matrix A @ B =\n{a @ b}")

 Matrix_1 = 
[[2 5 8]
 [3 2 5]
 [9 5 2]]

 Matrix_2 = 
[[ 2  9  5]
 [-2  3  6]
 [ 1 -2  5]]

Hasil perkalian Matrix_1 dan Matrix 2 = [[2, 17, 80], [7, 23, 52], [10, 92, 85]]

Pembuktian untuk Matrix A @ B =
[[ 2 17 80]
 [ 7 23 52]
 [10 92 85]]
